unstable_features=true
merge_imports=true
group_imports="StdExternalCrate"
edition="2018"
format_strings=true
normalize_comments=true
normalize_doc_attributes=true
reorder_impl_items=true
use_field_init_shorthand=true
wrap_comments=true
