[package]
name = "teamwork_schema"
version = "0.1.0"
authors = ["Kyle McCarthy <km@kylemccarthy.io>"]
edition = "2018"


[dependencies]
teamwork_macros = { path = '../teamwork_macros' }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "1.6.0"
